// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6fXmMyW6yGXDyfnn76VBSsSYWV9Wl854',
    appId: '1:1044088011706:web:34c604398868fb8d4f7b83',
    messagingSenderId: '1044088011706',
    projectId: 'airguard-webapp',
    authDomain: 'airguard-webapp.firebaseapp.com',
    storageBucket: 'airguard-webapp.firebasestorage.app',
    measurementId: 'G-VKG9VEFJ0V',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6fXmMyW6yGXDyfnn76VBSsSYWV9Wl854',
    appId: '1:1044088011706:web:1a209fb153dec0244f7b83',
    messagingSenderId: '1044088011706',
    projectId: 'airguard-webapp',
    authDomain: 'airguard-webapp.firebaseapp.com',
    storageBucket: 'airguard-webapp.firebasestorage.app',
    measurementId: 'G-PY1BRLDKMW',
  );

}